title: Ayume Milagres  
email: ayumilagres@gmail.com
description: >-
  Ayume's portfolio of data projects and storytelling.
baseurl: ""
url: "https://yourusername.github.io"
theme: jekyll-theme-minimal
markdown: kramdown

plugins:
  - jekyll-feed

